apiVersion: v2
name: hermes-agent-deployer-chart
description: A Helm chart for the Hermes Agent Deployer RHOAI community plugin
type: application
version: 0.2.0
appVersion: "0.2.0"
keywords:
  - rhoai
  - openshift-ai
  - plugin
  - hermes
  - agent
home: https://github.com/rh-ai-community-plugins/hermes-agent-deployer
sources:
  - https://github.com/rh-ai-community-plugins/hermes-agent-deployer
