apiVersion: v1
kind: Service
metadata:
  name: {{ include "hermes-agent-deployer.fullname" . }}
  labels:
    {{- include "hermes-agent-deployer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "hermes-agent-deployer.selectorLabels" . | nindent 4 }}
